
DECLARE @Success BIT, @Id INT, @TransactionId INT
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'14 Apr 2025',@Description = N'Greeting Cards',@Amount = 31.55,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 111,@Date = N'21 Apr 2025',@Description = N'Skincare sales',@Amount = 9.34,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'22 Apr 2025',@Description = N'art2arts feature',@Amount = 25,@ContactId = 18,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'23 Apr 2025',@Description = N'Art Prints',@Amount = 62.8,@ContactId = 2,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'23 Apr 2025',@Description = N'Greeting Cards',@Amount = 63.15,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'03 May 2025',@Description = N'Amazon art pens',@Amount = 30.96,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'06 May 2025',@Description = N'Giclee prints',@Amount = 39.6,@ContactId = 2,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'09 May 2025',@Description = N'Amazon, mounts',@Amount = 4.19,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'10 May 2025',@Description = N'P Pigram table for art fair Conwy Sept',@Amount = 60,@ContactId = 17,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'10 May 2025',@Description = N'zazzle, business cards',@Amount = 24.47,@ContactId = 15,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'13 May 2025',@Description = N'The range frames ',@Amount = 25.42,@ContactId = 14,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'13 May 2025',@Description = N'Amazon frames',@Amount = 97.74,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'01 May 2025',@Description = N'Alison''s bench original sold',@Amount = 40,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'06 May 2025',@Description = N'Pastel sold post office ',@Amount = 20,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'12 May 2025',@Description = N'Cards sold post office',@Amount = 6,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'18 May 2025',@Description = N'Biodegradable photo bags ',@Amount = 12.69,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'18 May 2025',@Description = N'Graces giclee prints',@Amount = 44.4,@ContactId = 2,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'18 May 2025',@Description = N'3 mths rent for display at y-shed',@Amount = 45,@ContactId = 5,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'18 May 2025',@Description = N'Cards sold to sisters half price, 16 x £1.25',@Amount = 20,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 111,@Date = N'19 May 2025',@Description = N'Nathan D skincare order',@Amount = 24.5,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'19 May 2025',@Description = N'The range, more frames and easels',@Amount = 19.81,@ContactId = 14,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'21 May 2025',@Description = N'Etsy flyers',@Amount = 7.95,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'21 May 2025',@Description = N'Etsy frame',@Amount = 13.48,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'24 May 2025',@Description = N'Printing tape ',@Amount = 10.99,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'21 May 2025',@Description = N'Amazon card stand',@Amount = 14.24,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'25 May 2025',@Description = N'Pennybatch greeting cards',@Amount = 81.95,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 115,@Date = N'28 May 2025',@Description = N'Post Office, charity auction mail',@Amount = 2,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'28 May 2025',@Description = N'Facebook Insta ads',@Amount = 6,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'28 May 2025',@Description = N'Hawarden post office sale of 5 cards',@Amount = 10,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'07 Jun 2025',@Description = N'Amazon Greeting card stand 2',@Amount = 17.99,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'09 Jun 2025',@Description = N'Frame from Etsy',@Amount = 12.99,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'09 Jun 2025',@Description = N'red dots amazon',@Amount = 1.7,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 112,@Date = N'09 Jun 2025',@Description = N'VAA art membership and insurance',@Amount = 47.2,@ContactId = 19,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'09 Jun 2025',@Description = N'Mounts from Etsy',@Amount = 1.9,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'10 Jun 2025',@Description = N'Card sale Hawarden Post Office',@Amount = 4,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'10 Jun 2025',@Description = N'Card sale Florist (Debra)',@Amount = 2,@ContactId = 10,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'10 Jun 2025',@Description = N'Card stand for Mary (Southport)',@Amount = 7.59,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'10 Jun 2025',@Description = N'Greeting cards',@Amount = 126.95,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'12 Jun 2025',@Description = N'10 Cards at forest Florist @£1.75 each',@Amount = 17.5,@ContactId = 10,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'12 Jun 2025',@Description = N'Facebook Insta ads',@Amount = 7,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'13 Jun 2025',@Description = N'Etsy Mounts ',@Amount = 9.7,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'13 Jun 2025',@Description = N'from paypal (after charges) print website order',@Amount = 28.82,@ContactId = 11,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'13 Jun 2025',@Description = N'Graces giclee prints',@Amount = 32.4,@ContactId = 2,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'15 Jun 2025',@Description = N'Hawarden post office sale of 2 prints (Al''s bench)',@Amount = 32,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'16 Jun 2025',@Description = N'Graces giclee prints',@Amount = 11,@ContactId = 2,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'20 Jun 2025',@Description = N'Amazon ',@Amount = 11.89,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'23 Jun 2025',@Description = N'Where can we go ad ',@Amount = 5,@ContactId = 20,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'23 Jun 2025',@Description = N'FB ad',@Amount = 5,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'24 Jun 2025',@Description = N'Sale cards from Hawarden Post office',@Amount = 8,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 113,@Date = N'24 Jun 2025',@Description = N'amazon Hanging stuff for exhibition',@Amount = 12.67,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'25 Jun 2025',@Description = N'Sumup machine ',@Amount = 22.8,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'26 Jun 2025',@Description = N'Southport Gym card sales',@Amount = 37.8,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'29 Jun 2025',@Description = N'Southport Gym card sales',@Amount = 5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'29 Jun 2025',@Description = N'Cass Art paper and pens',@Amount = 50.9,@ContactId = 21,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'02 Jul 2025',@Description = N'Southport Gym card sales',@Amount = 12.5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 113,@Date = N'04 Jul 2025',@Description = N'Asda, wine and nibbles ',@Amount = 60,@ContactId = 22,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'05 Jul 2025',@Description = N'Exhibition',@Amount = 428,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'08 Jul 2025',@Description = N'Card Southport',@Amount = 2.5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'09 Jul 2025',@Description = N'Hawarden post office bought 41 cards Cards at 1.75 each',@Amount = 71.75,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'10 Jul 2025',@Description = N'500 cards ordered from Pennybatch gallery',@Amount = 227.95,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'11 Jul 2025',@Description = N'Sold 5 cards southport gym',@Amount = 10,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 113,@Date = N'14 Jul 2025',@Description = N'Paid ANW for Bodnant Gardens exhibition',@Amount = 10,@ContactId = 17,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'18 Jul 2025',@Description = N'Sold 15 cards Hawarden post office',@Amount = 26.25,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'21 Jul 2025',@Description = N'4 cards at Y shed sold',@Amount = 9.82,@ContactId = 5,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'30 Jul 2025',@Description = N'30 cards sold at Hawarden Post Office',@Amount = 52.5,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'30 Jul 2025',@Description = N'10 Cards at forest Florist @£1.75 each',@Amount = 17.5,@ContactId = 10,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'01 Aug 2025',@Description = N'2 cards sold Y shed',@Amount = 4.91,@ContactId = 5,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'04 Aug 2025',@Description = N'Insta ad ',@Amount = 7,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'08 Aug 2025',@Description = N'Southport Gym card sales',@Amount = 2.5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'12 Aug 2025',@Description = N'25 cards sold to Hawarden Post Office ',@Amount = 43.75,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'15 Aug 2025',@Description = N'Calendar order',@Amount = 66.9,@ContactId = 23,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'15 Aug 2025',@Description = N'Christmas cards',@Amount = 69.95,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'15 Aug 2025',@Description = N'Southport Gym card sales',@Amount = 5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 113,@Date = N'18 Aug 2025',@Description = N'Open art entry ',@Amount = 10,@ContactId = 25,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'21 Aug 2025',@Description = N'Southport Gym card sales',@Amount = 5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'26 Aug 2025',@Description = N'Insta ad ',@Amount = 0.99,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'27 Aug 2025',@Description = N'Insta ad ',@Amount = 5,@ContactId = 16,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'27 Aug 2025',@Description = N'Paula Adams Commission',@Amount = 165,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 8,@Date = N'01 Sep 2025',@Description = N'Y-shed rent (para el mund)',@Amount = 15,@ContactId = 5,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'04 Sep 2025',@Description = N'Y-shed rent (para el mund)',@Amount = 19.65,@ContactId = 5,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'04 Sep 2025',@Description = N'Southport Gym card sales',@Amount = 2.5,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'06 Sep 2025',@Description = N'The Glynne print sold',@Amount = 20,@ContactId = 9,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'07 Sep 2025',@Description = N'Pennybatch order greeting Cards',@Amount = 81.95,@ContactId = 1,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'07 Sep 2025',@Description = N'Sisters purchased xmas cards (faulty) x 20',@Amount = 10,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'08 Sep 2025',@Description = N'Print sold at Hawarden Post office',@Amount = 16,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'08 Sep 2025',@Description = N'20 cards sold to Hawarden Post Office',@Amount = 35,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 6,@Date = N'09 Sep 2025',@Description = N'Love from the artist (Transarnia) prints and cards',@Amount = 32.34,@ContactId = 24,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'10 Sep 2025',@Description = N'Print sold at Hawarden Post office',@Amount = 16,@ContactId = 4,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'12 Sep 2025',@Description = N'Calendar sold (to Nic)',@Amount = 11,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 3,@AccountId = 110,@Date = N'14 Sep 2025',@Description = N'2 x Calendars sold on Etsy',@Amount = 29.98,@ContactId = 3,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 116,@Date = N'15 Sep 2025',@Description = N'Etsy fee',@Amount = 4.5,@ContactId = 13,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'16 Sep 2025',@Description = N'Amazon card stand',@Amount = 8.99,@ContactId = 12,@CurrentUserId = 1
EXEC [finance].[Transaction_CreateExpenseIncome] @Success = @Success OUTPUT,@Id = @Id OUTPUT,@TransactionId = @Id OUTPUT,@TransactionTypeId = 2,@AccountId = 114,@Date = N'16 Sep 2025',@Description = N'Amazon,backing card and envelopes',@Amount = 14.98,@ContactId = 12,@CurrentUserId = 1
